import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Landing Page Design Tokens (prefixed with lp- where they overlap with existing keywords)
        "surface-container": "#1f1f26",
        "surface-container-highest": "#35343b",
        "on-tertiary-fixed-variant": "#004e5c",
        "primary-fixed": "#d8e2ff",
        "on-tertiary": "#003640",
        "surface-container-lowest": "#0e0e14",
        "on-primary-fixed": "#001a40",
        "secondary-container": "#571bc1",
        "inverse-primary": "#005bbf",
        "on-surface-variant": "#c1c6d6",
        "lp-primary": "#acc7ff",
        "on-primary-fixed-variant": "#004492",
        "on-primary": "#002e68",
        "on-tertiary-container": "#002f38",
        "lp-secondary": "#d0bcff",
        "on-secondary": "#3c0091",
        "on-secondary-fixed": "#23005c",
        "secondary-fixed-dim": "#d0bcff",
        "lp-surface": "#131319",
        "lp-background": "#131319",
        "lp-outline": "#8c909f",
        "lp-error": "#ffb4ab",
        "surface-dim": "#131319",
        "on-secondary-fixed-variant": "#5516be",
        "on-secondary-container": "#c4abff",
        "primary-fixed-dim": "#acc7ff",
        "inverse-surface": "#e4e1ea",
        "surface-tint": "#acc7ff",
        "on-background": "#e4e1ea",
        "on-surface": "#e4e1ea",
        "inverse-on-surface": "#303037",
        "primary-container": "#498eff",
        "surface-bright": "#393840",
        "tertiary": "#4cd7f6",
        "on-primary-container": "#00285b",
        "surface-container-high": "#2a2930",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#001f26",
        "on-error-container": "#ffdad6",
        "surface-variant": "#35343b",
        "secondary-fixed": "#e9ddff",
        "surface-container-low": "#1b1b22",
        "outline-variant": "#414753",
        "on-error": "#690005",
        "tertiary-fixed": "#acedff",
        "tertiary-fixed-dim": "#4cd7f6",
        "tertiary-container": "#009eb9",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        soft: "0 10px 30px rgba(15, 23, 42, 0.08)",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "xxl": "96px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px",
        "unit": "4px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        hanken: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
